#!/usr/bin/perl -w

# ===========================================================================
# File:		yp
# Purpose:	Generator for a Yawns-Planet website.
# Created:	2005-10-12
#
# ===========================================================================
# (c) 2005 Steve Kemp <steve@steve.org.uk>
# This program is free software; you can redistribute it and/or modify 
# it under the terms of version 2 of the GNU General Public License as 
# published by the Free Software Foundation.  See the file COPYING for 
# further details.
# ===========================================================================
#
# $Id: yp,v 1.2 2005-10-12 11:29:23 steve Exp $

# Enforce good programming practices
use strict;


# Modules we use.
use DBI;
use HTML::Template

#
#  1. Connect to the database
#
#  2. Get weblog posters.
#
#  3. Create output HTML
#
#  4. Create output XML feeds.
# 
#  5. Disconnect from database.
#




#
#  Return the relevent weblog entries from the database
#
sub getWeblogs()
{
    my ( $dbh, $count ) = ( @_ );

    #
    # Execute Query:
    #
    # SELECT a.gid,a.id, a.username, a.title, a.bodytext, a.ondate, count(b.id)
    #  FROM weblogs AS a
    #    INNER JOIN comments AS b
    #      ON a.gid=b.root AND b.type='w' 
    #      GROUP by a.ondate DESC LIMIT 0,$count;
    #
    #  Hmmm comments are counted in the weblogs table too:
    #
    # SELECT gid, id, username, title, bodytext, ondate,comments
    #  FROM weblogs 
    #   ORDER BY ondate DESC LIMIT 0, $count
    #
    #
}
