#!/usr/bin/perl -w -I..
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

BEGIN{ use_ok( 'CGI' ); }
require_ok( 'CGI' );


BEGIN{ use_ok( 'conf::SiteConfig' ); }
require_ok( 'conf::SiteConfig' );


BEGIN{ use_ok( 'Date::Manip' ); }
require_ok( 'Date::Manip' );


BEGIN{ use_ok( 'DBI' ); }
require_ok( 'DBI' );


BEGIN{ use_ok( 'HTML::Cleanup' ); }
require_ok( 'HTML::Cleanup' );


BEGIN{ use_ok( 'HTML::Entities' ); }
require_ok( 'HTML::Entities' );


BEGIN{ use_ok( 'HTML::Parser' ); }
require_ok( 'HTML::Parser' );


BEGIN{ use_ok( 'HTML::Scrubber' ); }
require_ok( 'HTML::Scrubber' );


BEGIN{ use_ok( 'HTML::Template' ); }
require_ok( 'HTML::Template' );


BEGIN{ use_ok( 'HTML::TreeBuilder' ); }
require_ok( 'HTML::TreeBuilder' );


BEGIN{ use_ok( 'Singleton::DBI' ); }
require_ok( 'Singleton::DBI' );


BEGIN{ use_ok( 'strict' ); }
require_ok( 'strict' );


BEGIN{ use_ok( 'Test::More' ); }
require_ok( 'Test::More' );


BEGIN{ use_ok( 'vars' ); }
require_ok( 'vars' );


BEGIN{ use_ok( 'YawnsBlog' ); }
require_ok( 'YawnsBlog' );


